### ISSUE TITLE
[Proposal] Fix wrapper table

### ISSUE THREAD

**Issue by trigaten** [Farama-Foundation/gym-docs#140]
Currently, the individual wrappers are documented in a gigantic table here: [Wrappers - Gym Documentation](https://www.gymlibrary.ml/content/wrappers/#available-wrappers). The table is confusing. Should we have one auto-generated page per wrapper (not including the abstract super-classes) and list them on the main page?
- @Markus28

**Comment by pseudo-rnd-thoughts** [comment]
In the near future, we will be releasing a new set of wrappers to replace the old ones. So it would be nice to have some auto gen code to use the docstrings for the wrappers. So it might to worth using that code for the current wrappers as well

These wrappers will be split into several helpful categories, lambda observation wrappers, step wrappers, stateful wrappers, etc. My plan is for these wrappers to have large and well-documented docstrings so I think a page for each of these wrapper categories will be necessary.
