### ISSUE TITLE
Minor error in vector API reset method

### ISSUE THREAD

**Issue by DDDOH** [Farama-Foundation/gym-docs#150]
For the vector API, reset method (https://www.gymlibrary.ml/content/vector_api/#reset), currently it shows
<img width="777" alt="image" src="https://user-images.githubusercontent.com/25512742/173235278-7f78680d-8f5c-4980-adc3-1ece6e1fea22.png">
Note that for the parameter "options" - If to return the options
I doubt the actually meaning is
<img width="826" alt="image" src="https://user-images.githubusercontent.com/25512742/173235317-0a9625f0-46a2-4e22-8059-f0c717c59ede.png">
that is options actually is the reset option

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for spotting this, we will update it

**Comment by DDDOH** [comment]
By the way, is it possible to pass different options for each of the environment in VecEnv, like how we handle the seed argument? The current implementation can only pass the same option to all the environments. Although we can pass a single option (which is actually a list of options) to every environment, and let each environment read its own option from the list, but I think it's better if there's an elegant official API.

**Comment by DDDOH** [comment]
Definitely will do! The implementation should not be that difficult.
________________________________
发件人: Mark Towers ***@***.***>
发送时间: Monday, June 13, 2022 7:20:47 PM
收件人: Farama-Foundation/gym-docs ***@***.***>
抄送: Shuffle-Official ***@***.***>; Author ***@***.***>
主题: Re: [Farama-Foundation/gym-docs] Minor error in vector API reset method (Issue #150)


Interesting idea, currently that is not a feature, would you want to make the PR?

―
