### ISSUE TITLE
Problem with rendering

### ISSUE THREAD

**Issue by Raagulbharatwaj** [Farama-Foundation/gym-docs#175]
I am trying to create a Q-learning agent  I am having a problem with rendering the environment. I want to render the environment every thousand episodes but due to env.reset() calling render internally the rendering is continuous and the training is so slow.

**Comment by pseudo-rnd-thoughts** [comment]
You are asking in the wrong project, could you make an issue https://github.com/farama-Foundation/gymnasium here with some example code to help understand your problem
